---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        args:
          - --kubelet-insecure-tls
