apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanfoster/gitops-bridge-argocd.git
    targetRevision: main
    path: charts/monitoring
    helm:
      valuesObject:
        global:
          destination:
            name: gitops-bridge-argocd-dev
        k8sMonitoring:
          cluster:
            name: gitops-bridge-argocd-dev
  destination:
    name: gitops-bridge-argocd-dev
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
