{{- if and (.Values.externalSecrets) (.Values.externalSecrets.enabled) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: {{ .Values.global.namespace | default "argocd" }}
spec:
  project: {{ .Values.global.project | default "default" }}
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.20
    helm:
      values: |
        {{- toYaml (omit .Values.externalSecrets "enabled") | nindent 8 }}
  destination:
    server: {{ .Values.global.destination.server | default "https://kubernetes.default.svc" }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end -}}
