global:
  namespace: argocd
  project: default
  source:
    repoURL: https://github.com/jonathanfoster/gitops-bridge-argocd.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
kubePrometheusStack:
  enabled: true
