global:
  namespace: argocd
  project: default
  source:
    repoURL: https://github.com/jonathanfoster/gitops-bridge-argocd.git
    targetRevision: main
  destination:
    name: in-cluster
    namespace: kube-system
awsEbsCsiDriver:
  enabled: true
awsEfsCsiDriver:
  enabled: true
awsLoadBalancerController:
  enabled: true
certManager:
  enabled: true
  crds:
    enabled: true
clusterAutoscaler:
  enabled: true
externalDns:
  enabled: true
externalSecrets:
  enabled: true
ingressNginx:
  enabled: true
metricsServer:
  enabled: true
