{{- if and (.Values.kubePrometheusStack) (.Values.kubePrometheusStack.enabled) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: {{ .Values.global.namespace | default "argocd" }}
spec:
  project: {{ .Values.global.project | default "default" }}
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: {{ (.Values.kubePrometheusStack.source).targetRevision | default "61.*" }}
    helm:
      values: |
        {{- toYaml (omit .Values.kubePrometheusStack "enabled") | nindent 8 }}
  destination:
    name: {{ .Values.global.destination.name | default "in-cluster" }}
    namespace: {{ .Values.global.destination.namespace | default "monitoring" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end -}}
