apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: add-ons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanfoster/gitops-bridge-argocd.git
    targetRevision: main
    path: charts/add-ons
    helm:
      releaseName: add-ons
      values: |
        awsEbsCsiDriver:
          enabled: false
        awsEfsCsiDriver:
          enabled: false
        awsLoadBalancerController:
          enabled: false
        ingressNginx:
          controller:
            service:
              type: NodePort
        metricsServer:
          args:
            - --kubelet-insecure-tls
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
