apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanfoster/gitops-bridge-argocd.git
    targetRevision: main
    path: charts/monitoring
    helm:
      values: |
        kubePrometheusStack:
          enabled: true
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
