{{- if and (.Values.metricsServer) (.Values.metricsServer.enabled) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: {{ .Values.global.namespace | default "argocd" }}
spec:
  project: {{ .Values.global.project | default "default" }}
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: {{ (.Values.metricsServer.source).targetRevision | default "3.*" }}
    helm:
      values: |
        {{- toYaml (omit .Values.metricsServer "enabled") | nindent 8 }}
  destination:
    name: {{ .Values.global.destination.name | default "in-cluster" }}
    namespace: {{ .Values.global.destination.namespace | default "kube-system" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end -}}
